### ISSUE TITLE
Blogish explanation doesn't underline the importance of -K

### ISSUE THREAD

**Issue by jjl** [tomoconnor/parallax#3]
My reading of it left it unclear that -K equated to "prompt for sudo password".

```
For the first run, we'll need to tell ansible the SSH and Sudo passwords, because one of the thing that the common role does is to configure passwordless sudo, and deploy a SSH key.
```

This bit makes sense, though you then don't go and configure it to do passwordless sudo, so it's a touch confusing. I did eventually figure it out because you'd supplied two flags to the ansible-playbook command.

```
In order to use Ansible with SSH passwords (pretty much required for the first run of normal machines (unless you deploy keys with something far lower level, like kickstart), you'll need the sshpass program. 
```

This is probably why I got a touch confused about it. I'd also note that mac users (i.e. Me!) are SOL when it comes to installing sshpass easily (homebrew refuses to package it which means tedium):

```
custard-tart% brew install sshpass
Error: No available formula for sshpass
We won't add sshpass because it makes it too easy for novice SSH users to
ruin SSH's security.
```

Suggested fix: explain that `-k` is for providing an ssh password and `-K` is for providing a sudo password. Possibly link to somewhere to teach people how to configure passwordless sudo.

**Comment by tomoconnor** [comment]
I did,  originally have an insecure sudoers deployment play, but it got
loads of complaints.

Also,  sshpass _was_ brew installable, so if they've removed it,  that's a
regression..  I suspect there's a recipe for it somewhere.

I'll edit the article and probably add the insecure sudoers deployment back
in,  with more warnings.

T

**Comment by jjl** [comment]
It’s still installable directly from a github url to the original formula:

`brew install https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb`

/j

**Comment by tomoconnor** [comment]
I suspect if you looking at the history of commits for parallax you might
find that original sudoers deployment rune

**Comment by jjl** [comment]
Just found this too. Perhaps a good update to the blog?

https://github.com/Homebrew/homebrew/issues/25554#issuecomment-31360899

/j

**Comment by tomoconnor** [comment]
It's not Homebrew's place really.  They should empower users,  not troll
them.

**Comment by jjl** [comment]
I had meant the flags you could pass ansible listed by a randomer actually.

But homebrew do have a bit of form to be honest. The hoops I had to go through to get cask included were… severe.

https://github.com/Homebrew/homebrew/pull/23338

Can’t say I’m a massive fan of the PHP school of ‘save people from themselves’, but it’s not my project. I have several times contemplated setting up my own homebrew tap that’s less discriminatory.

James

**Comment by tomoconnor** [comment]
Unix has always been very clear on not saving people from themselves.  Rm
and dd are good example of that.

I deeply disagree with the philosophy that suggests that I don't know what
I'm doing.
